version: '3.4'
services:
    pydocs:
        image: 'henry2833/pydocs:worker'
        build:
            dockerfile: Dockerfile
            context: .
            network: pydocs-net
        environment:
            REDIS_PASSW: "${REDIS_PASSW}"
            SQL_CONN:  "${SQL_CONN}"
            REDIS_HOST: "${REDIS_HOST}"
            RQ_NAME: 'default'
            WORKER: 'true'
            HOMEDATAPATH: "/data/"
            HOMEPATH: '/app/'
        deploy:
            resources:
                limits:
                    memory: 160M
                reservations:
                    memory: 100M
        volumes:
            - type: bind
              source: ./data
              target: /data
    web:
        image: 'henry2833/pydocs:web'
        build:
            dockerfile: Dockerfile
            context: .
            network: pydocs-net
        environment:
            REDIS_PASSW: "${REDIS_PASSW}"
            SQL_CONN:  "${SQL_CONN}"
            REDIS_HOST: "${REDIS_HOST}"
            HOMEDATAPATH: "/data/"
            HOMEPATH: '/app/'
            PORT: 5000
        deploy:
            resources:
                limits:
                    memory: 400M
                reservations:
                    memory: 100M
        volumes:
            - type: bind
              source: ./data
              target: /data
    sql:
        image: 'henry2833/pydocs:sql'
        build:
            dockerfile: Dockerfile
            network: pydocs-net
            context: .
        environment:
            REDIS_PASSW: "${REDIS_PASSW}"
            SQL_CONN:  "${SQL_CONN}"
            REDIS_HOST: "${REDIS_HOST}"
            SQL_SERV: "true"
            HOMEDATAPATH: "/data/"
            HOMEPATH: '/app/'
        container_name: sql_serv
        volumes:
            - type: bind
              source: ./data
              target: /data



