version: '3.4'
services:
    pydocs:
        build:
            dockerfile: Dockerfile
            context: .
            network: pydocs-net
            args:
                REQ_FILE: 'pydocs_reqs.txt'
        image: henry2833/pydocs:latest
        environment:
            REDIS_PASSW: "${REDIS_PASSW}"
            SQL_CONN:  "${SQL_CONN}"
            REDIS_HOST: "${REDIS_HOST}"
            RQ_NAME: 'default'
            HOMEDATAPATH: ${HOMEDATAPATH}
            HOMEPATH: ${HOMEPATH}
            WORKER: 'true'
        deploy:
            resources:
                limits:
                    cpus: '0.7'
                    memory: 200M
                reservations:
                    memory: 100M
        volumes:
            - .:${HOMEPATH}
    web:
        image: 'henry2833/pydocs:latest'
        environment:
            REDIS_PASSW: "${REDIS_PASSW}"
            SQL_CONN:  "${SQL_CONN}"
            REDIS_HOST: "${REDIS_HOST}"
            HOMEDATAPATH: "${HOMEDATAPATH}"
            HOMEPATH: "${HOMEPATH}"
            PORT: 5000
            AZURESTORAGEKEY: "${AZURESTORAGEKEY}"
        deploy:
            resources:
                limits:
                    memory: 600M
                reservations:
                    memory: 200M
        ports:
            - target: 5000
              published: 80

        volumes:
            - .:${HOMEPATH}
    sql:
        image: 'henry2833/pydocs:latest'
        environment:
            REDIS_PASSW: "${REDIS_PASSW}"
            SQL_CONN:  "${SQL_CONN}"
            REDIS_HOST: "${REDIS_HOST}"
            SQL_SERV: "true"
            HOMEDATAPATH: "${HOMEDATAPATH}"
            HOMEPATH: "${HOMEPATH}"
            AZURESTORAGEKEY: "${AZURESTORAGEKEY}"
        #container_name: sql_serv
        volumes:
            - .:${HOMEPATH}



