version: '3.4'
services:
    pydocs:
        image: henry2833/pydocs:latest
        entrypoint: ['/bin/bash']
        environment:
            REDIS_PASSW: "${REDIS_PASSW}"
            SQL_CONN:  "${SQL_CONN}"
            REDIS_HOST: "${REDIS_HOST}"
            RQ_NAME: 'default'
            HOMEDATAPATH: ${HOMEDATAPATH}
            HOMEPATH: ${HOMEPATH}
            WORKER: 'true'
            AZURESTORAGEKEY: "${AZURESTORAGEKEY}"
        deploy:
            resources:
                limits:
                    cpus: '0.7'
                    memory: 200M
                reservations:
                    memory: 100M
        volumes:
            - type: bind
              source: .
              target: ${HOMEPATH}
    web:
        image: henry2833/pydocs:latest
        #Temporarily disable for debugging
        entrypoint: ['echo', 'Service disabled']
        environment:
            REDIS_PASSW: "${REDIS_PASSW}"
            SQL_CONN:  "${SQL_CONN}"
            REDIS_HOST: "${REDIS_HOST}"
            HOMEDATAPATH: "${HOMEDATAPATH}"
            HOMEPATH: "${HOMEPATH}"
            PORT: 5000
            AZURESTORAGEKEY: "${AZURESTORAGEKEY}"
        deploy:
            resources:
                limits:
                    memory: 600M
                reservations:
                    memory: 200M
        ports:
            - target: 5000
              published: 80
        volumes:
            - type: bind
              source: .
              target: ${HOMEPATH}

              #    sql:
              #        image: 'henry2833/pydocs:latest'
              #        environment:
              #            REDIS_PASSW: "${REDIS_PASSW}"
              #            SQL_CONN:  "${SQL_CONN}"
              #            REDIS_HOST: "${REDIS_HOST}"
              #            SQL_SERV: "true"
              #            HOMEDATAPATH: "${HOMEDATAPATH}"
              #            HOMEPATH: "${HOMEPATH}"
              #            AZURESTORAGEKEY: "${AZURESTORAGEKEY}"
              #        volumes:
              #            - type: bind
              #              source: .
              #              target: ${HOMEPATH}
              #
networks:
    default:
        external:
            name: pydocs-net
